// prod.js - prod keys - DO COMMIT
module.exports = {
    googleClientID: process.env.GOOGLE_CLIENT_ID,
    googleClientSecret: process.env.GOOGLE_CLIENT_SECRET,
    mongoURI: process.env.MONGO_URI,
    cookieKey: process.env.COOKIE_KEY,
    stripePublishableKey: process.env.STRIPE_PUBLISHABLE_KEY,
    stripeSecretKey: process.env.STRIPE_SECRET_KEY,
    sendGridKey: process.env.SEND_GRID_KEY,
    redirectDomain: process.env.REDIRECT_DOMAIN,
    leagueApiKey: process.env.RIOT_API_KEY,
    baseURL: process.env.RIOT_API_BASE_URL,
    continentalBaseUrl: process.env.RIOT_API_CONTINENTAL_URL,
    emailRedirectUrl: process.env.EMAIL_REDIRECT_URL,
    corsURL_1: process.env.CORS_URL_1,
    corsURL_2: process.env.CORS_URL_2,
    corsURL_3: process.env.CORS_URL_3,
    corsURL_4: process.env.CORS_URL_4,
    corsURL_5: process.env.CORS_URL_5,

    corsURL_6: process.env.CORS_URL_6,
    corsURL_7: process.env.CORS_URL_7,
    corsURL_8: process.env.CORS_URL_8,
    corsURL_9: process.env.CORS_URL_9,
    corsURL_10: process.env.CORS_URL_10,
    corsURL_11: process.env.CORS_URL_11,
    corsURL_12: process.env.CORS_URL_12,
    corsURL_13: process.env.CORS_URL_13,
};
